// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type GetMetadataResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProviderType         string                 `protobuf:"bytes,1,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	AccessProviderType   string                 `protobuf:"bytes,2,opt,name=access_provider_type,json=accessProviderType,proto3" json:"access_provider_type,omitempty"`
	ProtocolVersion      uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DeployCategory       string                 `protobuf:"bytes,4,opt,name=deploy_category,json=deployCategory,proto3" json:"deploy_category,omitempty"`
	DeployDisplayNameKey string                 `protobuf:"bytes,5,opt,name=deploy_display_name_key,json=deployDisplayNameKey,proto3" json:"deploy_display_name_key,omitempty"`
	AccessDisplayNameKey string                 `protobuf:"bytes,6,opt,name=access_display_name_key,json=accessDisplayNameKey,proto3" json:"access_display_name_key,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetadataResponse) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *GetMetadataResponse) GetAccessProviderType() string {
	if x != nil {
		return x.AccessProviderType
	}
	return ""
}

func (x *GetMetadataResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GetMetadataResponse) GetDeployCategory() string {
	if x != nil {
		return x.DeployCategory
	}
	return ""
}

func (x *GetMetadataResponse) GetDeployDisplayNameKey() string {
	if x != nil {
		return x.DeployDisplayNameKey
	}
	return ""
}

func (x *GetMetadataResponse) GetAccessDisplayNameKey() string {
	if x != nil {
		return x.AccessDisplayNameKey
	}
	return ""
}

type GetConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaRequest) Reset() {
	*x = GetConfigSchemaRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaRequest) ProtoMessage() {}

func (x *GetConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

type StringMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMap) Reset() {
	*x = StringMap{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMap) ProtoMessage() {}

func (x *StringMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMap.ProtoReflect.Descriptor instead.
func (*StringMap) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *StringMap) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetConfigSchemaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessSchemaJson []byte                 `protobuf:"bytes,1,opt,name=access_schema_json,json=accessSchemaJson,proto3" json:"access_schema_json,omitempty"`
	DeploySchemaJson []byte                 `protobuf:"bytes,2,opt,name=deploy_schema_json,json=deploySchemaJson,proto3" json:"deploy_schema_json,omitempty"`
	I18NResources    map[string]*StringMap  `protobuf:"bytes,3,rep,name=i18n_resources,json=i18nResources,proto3" json:"i18n_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigSchemaResponse) Reset() {
	*x = GetConfigSchemaResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaResponse) ProtoMessage() {}

func (x *GetConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigSchemaResponse) GetAccessSchemaJson() []byte {
	if x != nil {
		return x.AccessSchemaJson
	}
	return nil
}

func (x *GetConfigSchemaResponse) GetDeploySchemaJson() []byte {
	if x != nil {
		return x.DeploySchemaJson
	}
	return nil
}

func (x *GetConfigSchemaResponse) GetI18NResources() map[string]*StringMap {
	if x != nil {
		return x.I18NResources
	}
	return nil
}

type DeployRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LogLevel           string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	AccessConfigJson   string                 `protobuf:"bytes,2,opt,name=access_config_json,json=accessConfigJson,proto3" json:"access_config_json,omitempty"`
	ExtendedConfigJson string                 `protobuf:"bytes,3,opt,name=extended_config_json,json=extendedConfigJson,proto3" json:"extended_config_json,omitempty"`
	CertificatePem     string                 `protobuf:"bytes,4,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	PrivateKeyPem      string                 `protobuf:"bytes,5,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *DeployRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *DeployRequest) GetAccessConfigJson() string {
	if x != nil {
		return x.AccessConfigJson
	}
	return ""
}

func (x *DeployRequest) GetExtendedConfigJson() string {
	if x != nil {
		return x.ExtendedConfigJson
	}
	return ""
}

func (x *DeployRequest) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *DeployRequest) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

type DeployResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExtendedDataJson string                 `protobuf:"bytes,1,opt,name=extended_data_json,json=extendedDataJson,proto3" json:"extended_data_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *DeployResponse) GetExtendedDataJson() string {
	if x != nil {
		return x.ExtendedDataJson
	}
	return ""
}

type LogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimestampMilli int64                  `protobuf:"varint,1,opt,name=timestamp_milli,json=timestampMilli,proto3" json:"timestamp_milli,omitempty"`
	Level          int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data           map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTimestampMilli() int64 {
	if x != nil {
		return x.TimestampMilli
	}
	return 0
}

func (x *LogEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeployFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*DeployFrame_Log
	//	*DeployFrame_Result
	Frame         isDeployFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployFrame) Reset() {
	*x = DeployFrame{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployFrame) ProtoMessage() {}

func (x *DeployFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployFrame.ProtoReflect.Descriptor instead.
func (*DeployFrame) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *DeployFrame) GetFrame() isDeployFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *DeployFrame) GetLog() *LogEntry {
	if x != nil {
		if x, ok := x.Frame.(*DeployFrame_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *DeployFrame) GetResult() *DeployResponse {
	if x != nil {
		if x, ok := x.Frame.(*DeployFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isDeployFrame_Frame interface {
	isDeployFrame_Frame()
}

type DeployFrame_Log struct {
	Log *LogEntry `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type DeployFrame_Result struct {
	Result *DeployResponse `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*DeployFrame_Log) isDeployFrame_Frame() {}

func (*DeployFrame_Result) isDeployFrame_Frame() {}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x13certimate.plugin.v1\"\x14\n" +
	"\x12GetMetadataRequest\"\xae\x02\n" +
	"\x13GetMetadataResponse\x12#\n" +
	"\rprovider_type\x18\x01 \x01(\tR\fproviderType\x120\n" +
	"\x14access_provider_type\x18\x02 \x01(\tR\x12accessProviderType\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12'\n" +
	"\x0fdeploy_category\x18\x04 \x01(\tR\x0edeployCategory\x125\n" +
	"\x17deploy_display_name_key\x18\x05 \x01(\tR\x14deployDisplayNameKey\x125\n" +
	"\x17access_display_name_key\x18\x06 \x01(\tR\x14accessDisplayNameKey\"\x18\n" +
	"\x16GetConfigSchemaRequest\"\x8e\x01\n" +
	"\tStringMap\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.certimate.plugin.v1.StringMap.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x02\n" +
	"\x17GetConfigSchemaResponse\x12,\n" +
	"\x12access_schema_json\x18\x01 \x01(\fR\x10accessSchemaJson\x12,\n" +
	"\x12deploy_schema_json\x18\x02 \x01(\fR\x10deploySchemaJson\x12f\n" +
	"\x0ei18n_resources\x18\x03 \x03(\v2?.certimate.plugin.v1.GetConfigSchemaResponse.I18nResourcesEntryR\ri18nResources\x1a`\n" +
	"\x12I18nResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.certimate.plugin.v1.StringMapR\x05value:\x028\x01\"\xdd\x01\n" +
	"\rDeployRequest\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x12,\n" +
	"\x12access_config_json\x18\x02 \x01(\tR\x10accessConfigJson\x120\n" +
	"\x14extended_config_json\x18\x03 \x01(\tR\x12extendedConfigJson\x12'\n" +
	"\x0fcertificate_pem\x18\x04 \x01(\tR\x0ecertificatePem\x12&\n" +
	"\x0fprivate_key_pem\x18\x05 \x01(\tR\rprivateKeyPem\">\n" +
	"\x0eDeployResponse\x12,\n" +
	"\x12extended_data_json\x18\x01 \x01(\tR\x10extendedDataJson\"\xd9\x01\n" +
	"\bLogEntry\x12'\n" +
	"\x0ftimestamp_milli\x18\x01 \x01(\x03R\x0etimestampMilli\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x04 \x03(\v2'.certimate.plugin.v1.LogEntry.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\vDeployFrame\x121\n" +
	"\x03log\x18\x01 \x01(\v2\x1d.certimate.plugin.v1.LogEntryH\x00R\x03log\x12=\n" +
	"\x06result\x18\x02 \x01(\v2#.certimate.plugin.v1.DeployResponseH\x00R\x06resultB\a\n" +
	"\x05frame2\xb2\x02\n" +
	"\x0eDeployerPlugin\x12`\n" +
	"\vGetMetadata\x12'.certimate.plugin.v1.GetMetadataRequest\x1a(.certimate.plugin.v1.GetMetadataResponse\x12l\n" +
	"\x0fGetConfigSchema\x12+.certimate.plugin.v1.GetConfigSchemaRequest\x1a,.certimate.plugin.v1.GetConfigSchemaResponse\x12P\n" +
	"\x06Deploy\x12\".certimate.plugin.v1.DeployRequest\x1a .certimate.plugin.v1.DeployFrame0\x01B4Z2github.com/certimate-go/certimate/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),      // 0: certimate.plugin.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),     // 1: certimate.plugin.v1.GetMetadataResponse
	(*GetConfigSchemaRequest)(nil),  // 2: certimate.plugin.v1.GetConfigSchemaRequest
	(*StringMap)(nil),               // 3: certimate.plugin.v1.StringMap
	(*GetConfigSchemaResponse)(nil), // 4: certimate.plugin.v1.GetConfigSchemaResponse
	(*DeployRequest)(nil),           // 5: certimate.plugin.v1.DeployRequest
	(*DeployResponse)(nil),          // 6: certimate.plugin.v1.DeployResponse
	(*LogEntry)(nil),                // 7: certimate.plugin.v1.LogEntry
	(*DeployFrame)(nil),             // 8: certimate.plugin.v1.DeployFrame
	nil,                             // 9: certimate.plugin.v1.StringMap.EntriesEntry
	nil,                             // 10: certimate.plugin.v1.GetConfigSchemaResponse.I18nResourcesEntry
	nil,                             // 11: certimate.plugin.v1.LogEntry.DataEntry
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	9,  // 0: certimate.plugin.v1.StringMap.entries:type_name -> certimate.plugin.v1.StringMap.EntriesEntry
	10, // 1: certimate.plugin.v1.GetConfigSchemaResponse.i18n_resources:type_name -> certimate.plugin.v1.GetConfigSchemaResponse.I18nResourcesEntry
	11, // 2: certimate.plugin.v1.LogEntry.data:type_name -> certimate.plugin.v1.LogEntry.DataEntry
	7,  // 3: certimate.plugin.v1.DeployFrame.log:type_name -> certimate.plugin.v1.LogEntry
	6,  // 4: certimate.plugin.v1.DeployFrame.result:type_name -> certimate.plugin.v1.DeployResponse
	3,  // 5: certimate.plugin.v1.GetConfigSchemaResponse.I18nResourcesEntry.value:type_name -> certimate.plugin.v1.StringMap
	0,  // 6: certimate.plugin.v1.DeployerPlugin.GetMetadata:input_type -> certimate.plugin.v1.GetMetadataRequest
	2,  // 7: certimate.plugin.v1.DeployerPlugin.GetConfigSchema:input_type -> certimate.plugin.v1.GetConfigSchemaRequest
	5,  // 8: certimate.plugin.v1.DeployerPlugin.Deploy:input_type -> certimate.plugin.v1.DeployRequest
	1,  // 9: certimate.plugin.v1.DeployerPlugin.GetMetadata:output_type -> certimate.plugin.v1.GetMetadataResponse
	4,  // 10: certimate.plugin.v1.DeployerPlugin.GetConfigSchema:output_type -> certimate.plugin.v1.GetConfigSchemaResponse
	8,  // 11: certimate.plugin.v1.DeployerPlugin.Deploy:output_type -> certimate.plugin.v1.DeployFrame
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	file_pkg_plugin_proto_plugin_proto_msgTypes[8].OneofWrappers = []any{
		(*DeployFrame_Log)(nil),
		(*DeployFrame_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
